name: 'GitHub Actions KZZ Reminder Bot...'

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@master
      - name: 'Pip install ics'
        run: pip3 install ics
      - name: 'Pip install requests'
        run: pip3 install requests         
      - name: 'Generate ics file'
        run: bash ./start.sh
      - name: 'Config user email'
        run:  git config --local user.email "action@github.com"
      - name: 'Config user name'
        run: git config --local user.name "GitHub Action"
      - name: 'Git diff'
        run: git diff
      - name: 'Git add '
        run: git add .
      - name: 'Git commit'
        run: git commit -m "Add changes"
      - name: 'GitHub Push'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
      - name: 'Print kzz.ics'
        run: cat ./kzz.ics

